quarkus.http.port=8080

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/order_db
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=false

quarkus.rest-client.inventory-api.url=http://inventory-service:8081
quarkus.rest-client.payment-api.url=http://payment-service:8082

quarkus.swagger-ui.always-include=true

quarkus.log.level=INFO
quarkus.log.category."br.com.tcc".level=DEBUG
quarkus.log.category."io.quarkus.rest.client".level=DEBUG

quarkus.log.console.enable=true
quarkus.log.console.level=DEBUG

quarkus.rest-client.logging.scope=request-response
quarkus.rest-client.logging.body=true
quarkus.rest-client.logging.body-limit=1024
quarkus.log.category."org.jboss.resteasy.reactive.client.logging".level=DEBUG
quarkus.log.category."org.jboss.resteasy.reactive.client".level=DEBUG
