quarkus.http.port=8080

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/order_db
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=false

quarkus.rest-client.inventory-api.url=http://inventory-service:8081
quarkus.rest-client.payment-api.url=http://payment-service:8082

quarkus.kafka.devservices.enabled=false
kafka.bootstrap.servers=kafka:29092

mp.messaging.outgoing.order-created.connector=smallrye-kafka
mp.messaging.outgoing.order-created.topic=order-created-events
mp.messaging.outgoing.order-created.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
mp.messaging.outgoing.order-created.retries=3
mp.messaging.outgoing.order-created.acks=all
mp.messaging.outgoing.order-created.kafka.retry.backoff.ms=1000
mp.messaging.outgoing.order-created.kafka.delivery.timeout.ms=10000
mp.messaging.outgoing.order-created.kafka.request.timeout.ms=5000

mp.messaging.incoming.payment-result-in.connector=smallrye-kafka
mp.messaging.incoming.payment-result-in.topic=payment-result-events
mp.messaging.incoming.payment-result-in.group.id=order-service-group
mp.messaging.incoming.payment-result-in.value.deserializer=br.com.tcc.orderservice.dtos.PaymentApprovedDeserializer
mp.messaging.incoming.payment-result-in.failure-strategy=dead-letter-queue
mp.messaging.incoming.payment-result-in.dead-letter-queue.topic=payment-result-dlq
mp.messaging.incoming.payment-result-in.dead-letter-queue.value.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.incoming.payment-result-in.dead-letter-queue.key.serializer=org.apache.kafka.common.serialization.StringSerializer

mp.messaging.incoming.inventory-failed-in.connector=smallrye-kafka
mp.messaging.incoming.inventory-failed-in.topic=inventory-failed-events
mp.messaging.incoming.inventory-failed-in.group.id=order-service-group
mp.messaging.incoming.inventory-failed-in.value.deserializer=br.com.tcc.orderservice.dtos.InventoryFailedDeserializer
mp.messaging.incoming.inventory-failed-in.failure-strategy=dead-letter-queue
mp.messaging.incoming.inventory-failed-in.dead-letter-queue.topic=inventory-failed-dlq
mp.messaging.incoming.inventory-failed-in.dead-letter-queue.value.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.incoming.inventory-failed-in.dead-letter-queue.key.serializer=org.apache.kafka.common.serialization.StringSerializer

mp.messaging.incoming.payment-failed-in.connector=smallrye-kafka
mp.messaging.incoming.payment-failed-in.topic=payment-failed-events
mp.messaging.incoming.payment-failed-in.group.id=order-service-group
mp.messaging.incoming.payment-failed-in.value.deserializer=br.com.tcc.orderservice.dtos.PaymentFailedDeserializer
mp.messaging.incoming.payment-failed-in.failure-strategy=dead-letter-queue
mp.messaging.incoming.payment-failed-in.dead-letter-queue.topic=payment-failed-dlq
mp.messaging.incoming.payment-failed-in.dead-letter-queue.value.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.incoming.payment-failed-in.dead-letter-queue.key.serializer=org.apache.kafka.common.serialization.StringSerializer

quarkus.swagger-ui.always-include=true

quarkus.log.level=INFO
quarkus.log.category."br.com.tcc".level=DEBUG
quarkus.log.category."io.quarkus.rest.client".level=DEBUG

quarkus.log.console.enable=true
quarkus.log.console.level=DEBUG

quarkus.rest-client.logging.scope=request-response
quarkus.rest-client.logging.body=true
quarkus.rest-client.logging.body-limit=1024
quarkus.log.category."org.jboss.resteasy.reactive.client.logging".level=DEBUG
quarkus.log.category."org.jboss.resteasy.reactive.client".level=DEBUG
